# -*- coding: utf-8 -*-
"""TEKMASI FIXX

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlrszPw_uUVYRgH5m3J8rDWhzKw-NiE_
"""

import pandas as pd
import numpy as np

import pandas as pd

df = pd.read_csv('/content/online_retail_II.csv')

df.head()

df.info()

df.isnull().sum()

df = df.dropna()

df = df.drop_duplicates()

df = df[~df['Invoice'].astype(str).str.contains('C')]

df['TotalPrice'] = df['Quantity'] * df['Price']

import datetime as dt

NOW = dt.datetime(2011,12,10)

rfm = df.groupby('Customer ID').agg({
    'InvoiceDate': lambda x: (NOW - x.max()).days,
    'Invoice': 'count',
    'TotalPrice': 'sum'
})

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

import pandas as pd

df = pd.read_csv('/content/online_retail_II.csv')

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['TotalPrice'] = df['Quantity'] * df['Price']

import pandas as pd
import numpy as np
import datetime as dt

df = pd.read_csv('/content/online_retail_II.csv')

df['InvoiceDate'] = pd.to_datetime(
    df['InvoiceDate'],
    errors='coerce'
)

df = df.dropna(subset=['InvoiceDate'])

df['TotalPrice'] = df['Quantity'] * df['Price']

NOW = dt.datetime(2011,12,10)

rfm = df.groupby('Customer ID').agg({
    'InvoiceDate': lambda x: (NOW - x.max()).days,
    'Invoice': 'count',
    'TotalPrice': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']

rfm.head()

rfm.isnull().sum()

rfm = rfm.head(100)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

rfm_scaled = scaler.fit_transform(rfm)

rfm_scaled = pd.DataFrame(
    rfm_scaled,
    columns=['Recency', 'Frequency', 'Monetary']
)

rfm_scaled.head()

rfm_scaled.to_csv('dataset_clean.csv', index=False)

from sklearn.model_selection import train_test_split

X_train, X_temp = train_test_split(
    rfm_scaled,
    test_size=0.30,
    random_state=42
)

X_val, X_test = train_test_split(
    X_temp,
    test_size=0.50,
    random_state=42
)

print("Train :", len(X_train))
print("Validation :", len(X_val))
print("Test :", len(X_test))

print("Train :", len(X_train))
print("Validation :", len(X_val))
print("Test :", len(X_test))

X_train.to_csv('train.csv', index=False)

X_val.to_csv('validation.csv', index=False)

X_test.to_csv('test.csv', index=False)

from google.colab import files

files.download('train.csv')

files.download('validation.csv')

files.download('test.csv')